# Generated by Django 4.0.1 on 2022-01-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='phone number'),
        ),
    ]
