# Generated by Django 4.0.1 on 2022-01-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='phone number'),
        ),
    ]
